### ISSUE TITLE
Improve date handling for DateParser

### ISSUE THREAD

**Issue by srschaecher** [F3Nation-Community/PAXminer#10]
From KSHE (JeffCo):
I pulled the relevant parts of bdminer.py and recreated the issue. It looks like on line 217, it calls "dateparser.parse(dateline) and with the terribly formatted date we used, it returns "2023-07-31 07:21:00", which is the current date, but the hour/minute from the bad input date. The error handling used in this section of code expects a return value of "None" for invalid dates, but that is not what we are getting.
I was able to get the expected behavior (return "None") by making the following change.
--dateline = dateparser.parse(dateline) #dateparser is a flexible date module that can understand many different date formats
++dateline = dateparser.parse(dateline, settings={'STRICT_PARSING': True}) #dateparser is a flexible date module that can understand many different date formats

**Comment by farrellw** [comment]
Added date handling in this MR: https://github.com/F3Nation-Community/PAXminer/pull/20

The bad formatting seemed to have stemmed mostly from people appending the timestamp to their date e.g. 02/15/2024 0530. Added rules around dates too many days from the past, too many days in the future which catches these bad formatting mistakes.

**Comment by farrellw** [comment]
Closing, ticket addressed in #20
