### ISSUE TITLE
Add YTD total to monthly posting summary

### ISSUE THREAD

**Issue by glenncarr** [F3Nation-Community/PAXminer#12]
Any chance the total number of postings for the year could be added to the following graph?
![image](https://github.com/F3Nation-Community/PAXminer/assets/367292/2126d5e9-47ca-40a8-8d32-7cfbc84be370)

**Comment by farrellw** [comment]
@glenncarr Thanks for raising the issue. This has been added within the larger MR #44 and will be included in the September stats ( Posted October 1st )
