### ISSUE TITLE
Set error DM to once per day

### ISSUE THREAD

**Issue by drewlarson1** [F3Nation-Community/PAXminer#17]
When PAX incorrectly enters a backblast, or there is unexpected behavior, the PAXMiner pings them hourly with the same message about the error. This results in frustration and hate for the PAXminer by anyone on the receiving end. They often then complain publicly, or privately. We've end had one guy simply refuse to enter backblasts anymore after being harassed too much. 

Please change the setting to one DM per day OR add an optional timeframe in the configuration settings.

Griswold (F3xT)

**Comment by farrellw** [comment]
@drewlarson1 thanks for submitting the issue.

With how PAXMiner is currently set up, this isn't possible to ping only once a day. Paxminer looks for backblasts every hour on the hour, and doesn't log failed attempts in the datastore.  So it sends a message as a failure each time it looks at the new message. It would be moderate to significant amount of effort, but I think a quicker solution might be to use "slackblast" to avoid this frustration.  I don't think that slackblast would even let you submit a backblast without an actual Q. Is that correct @evanpetzoldt ?

**Comment by evanpetzoldt** [comment]
Ha yeah, "use Slackblast!" is my goto response, in fact part of why I wanted to build it the way I did (direct interface with the db) is to avoid these issues. Yes @farrellw , it's basically impossible to submit a bad backblast through Slackblast.

However, if we wanted to implement something like this into PAXminer, I think the best approach would be to set up a separate table (probably just within the `paxminer` schema) that PAXminer logs to whenever it sends an error message (key could be post timestamp). Before sending an error message, it could check that table to see how many times its already sent an error message. This will add latency to PAXminer's normal process, so it's not ideal.

**Comment by evanpetzoldt** [comment]
Actually, a simpler approach would be to just use timestamp to gauge whether to send an error message. And if we further wanted it to only send x times per day, we could set constraints on the hourly run (only send if timestamp > 3 days ago and if current_time is between 3:00-4:00pm)

**Comment by farrellw** [comment]
How often do we want to bug someone to edit their backblast? 1x a day still might be a lot to some. One way to view this request is enabling people using paxminer for backblasts when the slackblast tool push model prevents this behavior. On the other hand, its improving the tool that many people use.

That being said, probably 1x a day + send on the first import immediately after it was posted makes sense as a place to start.

**Comment by drewlarson1** [comment]
First import and then daily makes the most sense to me.

**Comment by farrellw** [comment]
Sounds good. This MR posts once a day at 3pm and if it was posted within the last hour ( which is best estimate at first import ). Tested pinging off the F3-Nation-Community and dev instance, works with errors on the first import as well as error updates.

https://github.com/F3Nation-Community/PAXminer/pull/20

**Comment by farrellw** [comment]
Tested and works, closed.
