### ISSUE TITLE
Smarter backblast detection

### ISSUE THREAD

**Issue by evanpetzoldt** [F3Nation-Community/PAXminer#22]
It would be nice to close the loop on the issue of PAXminer trying to scrape any post that starts with "backblast"... This is a common mistake, and causes a lot of confusion. I would recommend that if a post has a trigger word but doesn't match on anything else (the DATE:, PAX:, etc lines) that we ignore. Or, we could say it has to be at least __ characters long.

Alternatively, maybe just a hint in the error message would suffice "hey, you may have accidentally started a message with 'backblast'"

**Comment by farrellw** [comment]
Right now, I think it's searching the entire string for backblast. Not even the first few words. We could probably get almost all of the way there by only looking at the first 40 characters of the string, or first line only.

**Comment by farrellw** [comment]
There is an actual minimum right now. 32 characters long for a full message, and has to contain some word similar to slackblast or backblast. 

What do we think the logic should be. 
```
length 32 ( or 40? ) 
AND 
contains backblast like word 
AND ( 
 AO: in backblast OR PAX: in backblast OR Date: in backblast OR Q: in backblast
 
```

**Comment by farrellw** [comment]
Deployed and running @evanpetzoldt.
