### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by drschimpf** [F3Nation-Community/PAXminer#27]
https://f3stlouis.com/paxminer/

I was looking on the website for setting up new AO's after someone had a question about the format. I noticed that in the documentation it states this: 

Total: Total number including Q, PAX, and FNGs. Number only, no text.

Shouldn't that be Count:  ?

I'm going to do an educational refresh for our PAX and want to make sure I publish the correct format for everyone, and I think this is wrong from what I could see in the code. I saw Count: not Total: but I'm a very basic programmer so could be reading it wrong.

**Comment by taterhead247** [comment]
Hey @drschimpf have you seen Slackblast? I’d highly recommend using that and not even telling people about this option. It will make your life way easier.

**Comment by drschimpf** [comment]
Yes I have...however you know some people prefer entering it this way no matter what other tools are there.

**Comment by srschaecher** [comment]
Both Count: and Total: are acceptable - you can use either.Sent from my iPhoneOn Aug 1, 2024, at 11:55 AM, drschimpf ***@***.***> wrote:﻿
Yes I have...however you know some people prefer entering it this way no matter what other tools are there.

**Comment by drschimpf** [comment]
Thanks!
