### ISSUE TITLE
Only Update User Profiles Who Have Changed

### ISSUE THREAD

**Issue by farrellw** [F3Nation-Community/PAXminer#37]
Update user process currently updates every single user, regardless if they have a change in their profile. This uses a lot of extra DB calls and time. Even if we look back 7 days ( way more than needed, would essentially need the process to fail 7 times in a row without retry to be out of date ), we cut down our database updates by 95%+

Something like this:
```
def user_lookback():
    SECONDS_PER_DAY = 86400
    LOOKBACK_DAYS = 7
    LOOKBACK_SECONDS = SECONDS_PER_DAY * LOOKBACK_DAYS
    current_ts = time.time()
    cutoff_ts = current_ts - LOOKBACK_SECONDS
    return cutoff_ts

for index, row in users_df[users_df['updated'] > cutoff_ts].iterrows():
```

**Comment by farrellw** [comment]
FYI @srschaecher. Deployed this for the user update script. This should only update users who profiles have changed in the last 7 days, which will significantly reduce the user update script run time and database calls.

**Comment by srschaecher** [comment]
Awesome, thanks!

From: Will Farrell ***@***.***>
Date: Tuesday, August 20, 2024 at 11:28 AM
To: F3Nation-Community/PAXminer ***@***.***>
Cc: srschaecher ***@***.***>, Mention ***@***.***>
Subject: Re: [F3Nation-Community/PAXminer] Only Update User Profiles Who Have Changed (Issue #37)

FYI @srschaecher<https://github.com/srschaecher>. Deployed this for the user update script. This should only update users who profiles have changed in the last 7 days, which will significantly reduce the user update script run time and database calls.
