### ISSUE TITLE
Issue: Can't DM Beaker (F3 STL) to get region enabled.

### ISSUE THREAD

**Issue by jeg924** [F3Nation-Community/PAXminer#42]
Hey guys, how do I follow this step:

>>>
Also under “OAuth & Permissions” – Find the “Bot User OAuth Access Token” and copy it. This shouldd be a big ugly string like “xoxb-XXXXXXX…”. Send this to Beaker (F3 STL) via slack DM. This is what he needs to get your region enabled.
>>>

From https://f3stlouis.com/paxminer-setup/

If Beaker isn't in my Slack workspace? Where's his contact info?

**Comment by farrellw** [comment]
@jeg924 Join the nation workspace, and start a DM with Beaker and Catalina. One of us will take care of it.

https://join.slack.com/t/f3nation/shared_invite/zt-2q66qp4eu-DhCZkWInVQs5u_JhqAjGZw

**Comment by farrellw** [comment]
Closing and redirecting to nation workspace.  https://join.slack.com/t/f3nation/shared_invite/zt-2q66qp4eu-DhCZkWInVQs5u_JhqAjGZw
