### ISSUE TITLE
Enhance User Table with Additional Fields

### ISSUE THREAD

**Issue by srschaecher** [F3Nation-Community/PAXminer#5]
Add the free text description from Slack to the Users table

**Comment by evanpetzoldt** [comment]
While we're making changes to the users table... Could we also add a json field? I have some ideas on using Slackblast to allow regions to collect extra info (birthday, emergency contact, etc) and store it there. We could add those fields directly, but I anticipate that regions would have different needs so would prefer to keep the format flexible.

**Comment by farrellw** [comment]
Hey y'all @srschaecher and @evanpetzoldt. This issue has been open awhile.

Seems similar to a couple recent requests around this stuff, so I'm going to repurpose this ticket. I made an MR to add a few details to the user table. 

The first is to insert the start_date into the user column. This is a default field in slack now, so it shows up in the user object when entered. This is going to really help people with their F3-Versary 
The second is to pick a few fields ( started with just isowner, isadmin, and updated ) and to add those to the JSON column in the user table. 

No changes to the user schema needed at all.

**Comment by farrellw** [comment]
Merged and deployed
